# Generated by Django 3.2.9 on 2022-01-03 13:11

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loop',
            name='short_timeout',
            field=models.CharField(default=2, max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
